const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({console, TextEncoder});
vm.runInContext(fs.readFileSync('web/dashboard_config.js', 'utf8').split("for (const key of ['a', 'b']) makeEditor(key);")[0], context);
const run = code => vm.runInContext(code, context);
const original = fs.readFileSync('qualification/phase8-v1.5.0-qual1/candidate_unitB.conf', 'utf8');
context.original = original;
run('var values = parseConfig(original); validateRF(values);');
assert.throws(() => run("validateRF({...values, TX_ATTENUATION_DB: '0.1'})"), /step/);
assert.throws(() => run("validateRF({...values, RX_GAIN_MODE: 'manual', RX_GAIN_DB: null})"), /gain/);
assert.throws(() => run("validateRF({...values, TX_RF_BANDWIDTH: '20000000'})"), /sample rate/);
assert.throws(() => run("validateRF({...values, FREQUENCY: values.RX_FREQUENCY})"), /differ/);
assert.throws(() => run("validateRF({...values, SAMPLE_RATE: '0'})"), /Sample rate/);
assert.throws(() => run("validateRF({...values, FREQUENCY: null})"), /frequency/);
run("validateRF({...values, TX_ATTENUATION_DB: '89.75', RX_GAIN_MODE: 'manual', RX_GAIN_DB: '73'})");
const patched = run("patchConfig(original, {TX_ATTENUATION_DB: '12.5'})");
assert.equal(run('parseConfig(original).NODE_ID'), run(`parseConfig(${JSON.stringify(patched)}).NODE_ID`));
assert(patched.endsWith('\n'));
assert.equal(run(`patchConfig(${JSON.stringify("# comment\nFOO=preserve\nRX_GAIN_DB=40\n")}, {RX_GAIN_DB: null})`), '# comment\nFOO=preserve\n');
fs.writeFileSync('/tmp/sdr-dashboard-candidate.conf', patched);
console.log('RF editor validation and config preservation tests passed');
