// Emits the HLS matched-filter coefficients from the SAME liquid prototype the
// host transmitter uses, so the fabric filter is genuinely matched rather than
// a hand-transcribed approximation.
#include <liquid/liquid.h>
#include <cstdio>
#include <vector>
int main(int argc, char** argv) {
    const unsigned sps = 4, m = 6;
    const float beta = 0.35f;
    const unsigned n = 2 * sps * m + 1;
    std::vector<float> h(n);
    liquid_firdes_prototype(LIQUID_FIRFILT_RRC, sps, m, beta, 0.0f, h.data());
    // Normalise on SUM of magnitudes, not peak.
    //
    // The FIR output is bounded by sum|h| times the peak input, so normalising
    // the peak tap to ~1 left sum|h| = 5.52 -- and the filter output then
    // could not fit fixp_t (ap_fixed<16,1>, range [-1,1)) or even acc_t
    // (range [-2,2)). Every strong sample saturated, which is why the
    // bypassed chain matched at chance level while a float reference using the
    // same taps recovered 253 of 256 bytes.
    //
    // Scaling by 1/sum|h| makes overflow impossible for any input in [-1,1).
    // It costs amplitude, which the AGC downstream removes anyway, and it does
    // not change the filter's shape -- only its gain.
    float sum = 0.f; for (float v : h) sum += (v > 0 ? v : -v);
    const float scale = 0.999f / sum;
    std::printf("/* RRC matched filter, generated by tools/gen_taps from the SAME\n"
                " * liquid prototype the transmitter uses:\n"
                " *   liquid_firdes_prototype(LIQUID_FIRFILT_RRC, sps=%u, m=%u, beta=%.2f)\n"
                " * -> 2*sps*m+1 = %u taps. Do not hand-edit; regenerate.\n"
                " *\n"
                " * The previous table claimed to be this filter but held 32 taps\n"
                " * spanning 8 symbols, so it was not the matched filter for the\n"
                " * transmitted pulse and nothing decoded at any sampling phase.\n"
                " */\n", sps, m, beta, n);
    std::printf("#define NTAPS %u\nstatic const fixp_t RRC_H[NTAPS] = {\n", n);
    for (unsigned i = 0; i < n; ++i) {
        if (i % 4 == 0) std::printf("   ");
        std::printf(" %9.6ff%s", h[i] * scale, (i + 1 < n) ? "," : "");
        if (i % 4 == 3 || i + 1 == n) std::printf("\n");
    }
    std::printf("};\n");
    return 0;
}
