#pragma once
// Shared types, constants and coefficients for the PlutoSDR QPSK modem cores.
//
// qpsk_demod.cpp and qpsk_mod.cpp are separate translation units on purpose.
// They used to share one file, and Vitis HLS re-parsed the whole thing once
// per solution: 33 s of the 108 s build was the demodulator's hls_math.h ->
// CORDIC/sqrt template instantiation, paid twice even though the modulator
// uses none of it. Splitting also gives each core its own project, so each can
// carry its own C testbench -- one project cannot hold two mains.
#include "ap_axi_sdata.h"
#include "ap_fixed.h"
#include "ap_int.h"
#include "hls_stream.h"
// NOTE: hls_math.h is deliberately NOT included here. Only the demodulator
// needs sqrt/cos/sin, and its template instantiation is the single largest
// cost in the build. qpsk_demod.cpp includes it directly.

/* ── Precision typedefs ─────────────────────────────────────────────
 * ap_fixed<W,I> = W total bits, I integer bits (W-I fractional bits)
 * Using 16-bit with 1 integer + 15 fractional for normalized IQ.
 */
typedef ap_fixed<16, 1>  fixp_t;    /* [-1, 1) normalized sample */
/* Accumulator. Four integer bits, range [-8,8): a partial sum inside the FIR
 * can exceed the final result, and the old ap_fixed<32,2> capped at 2.0 and
 * saturated mid-accumulation even once the taps were normalised. */
typedef ap_fixed<32, 4>  acc_t;
/* Carrier phase, in radians.
 *
 * Needs at least +-pi = 3.14159, which acc_t (ap_fixed<32,2>, range [-2,2))
 * cannot represent -- the Costas accumulator saturated at 1.99999 and stopped
 * tracking, so the loop never actually rotated anything. Four integer bits
 * give [-8,8): room for +-pi plus the overshoot before wrapping. */
typedef ap_fixed<32, 4>  phase_t;
typedef ap_uint<8>        byte_t;

/* ── AXI4-Stream types ────────────────────────────────────────────
 * ap_axiu, not a plain struct, and that distinction is the whole reason these
 * cores could not be attached to an AXI DMA.
 *
 * A bare `struct { ap_int<16> i, q; ap_uint<1> last; }` is aggregated by HLS
 * into TDATA and nothing else. The exported IP came out with a 48-bit
 * s_axis_iq TDATA and a 24-bit m_axis_bits TDATA, and no TLAST or TKEEP on
 * either: `last` was a payload bit that no downstream IP has any reason to
 * interpret. AXI DMA in simple mode needs a real TLAST to terminate an S2MM
 * transfer, and 24 bits is not a legal AXI4-Stream width in the first place.
 *
 * ap_axiu<W,0,0,0> carries TDATA/TKEEP/TSTRB/TLAST as proper side channels,
 * which makes the widths a clean 32 and 8 and puts TLAST where the DMA looks
 * for it.
 *
 * I and Q are packed little-endian into one 32-bit word rather than kept as
 * two struct fields, because that is the layout every other IP on this bus
 * already uses -- the ADI AD9361 core, the DMA, and the host's interleaved
 * int16 capture files alike.
 */
typedef ap_axiu<32, 0, 0, 0> IQSample;   /* data[15:0] = I, data[31:16] = Q */
typedef ap_axiu<8, 0, 0, 0>  BitByte;    /* data = one payload byte        */

/* TKEEP/TSTRB must be all ones on every beat or a DMA will treat the bytes as
 * null and drop them. Set through one helper so no output path can forget. */
template <typename T> static inline void axis_mark(T& t, bool last) {
#pragma HLS INLINE
    t.keep = -1;
    t.strb = -1;
    t.last = last ? 1 : 0;
}

/* RRC matched filter, generated by tools/gen_taps from the SAME
 * liquid prototype the transmitter uses:
 *   liquid_firdes_prototype(LIQUID_FIRFILT_RRC, sps=4, m=6, beta=0.35)
 * -> 2*sps*m+1 = 49 taps. Do not hand-edit; regenerate.
 *
 * The previous table claimed to be this filter but held 32 taps
 * spanning 8 symbols, so it was not the matched filter for the
 * transmitted pulse and nothing decoded at any sampling phase.
 */
#define NTAPS 49
/* Samples per symbol in fabric, and the depth of each polyphase sub-filter.
 * Sub-filter k uses taps k, k+SPS, k+2*SPS, ... so it needs ceil(NTAPS/SPS)
 * symbol history, not NTAPS. */
#define RRC_SPS_HW      4
#define TAPS_PER_PHASE  ((NTAPS + RRC_SPS_HW - 1) / RRC_SPS_HW)
static const fixp_t RRC_H[NTAPS] = {
    -0.000967f, -0.000741f,  0.000454f,  0.001516f,
     0.001238f, -0.000392f, -0.001919f, -0.001695f,
     0.000337f,  0.002198f,  0.001580f, -0.001576f,
    -0.004200f, -0.002438f,  0.004227f,  0.010783f,
     0.009426f, -0.003642f, -0.022304f, -0.031127f,
    -0.013975f,  0.034137f,  0.100291f,  0.157940f,
     0.180795f,  0.157940f,  0.100291f,  0.034137f,
    -0.013975f, -0.031127f, -0.022304f, -0.003642f,
     0.009426f,  0.010783f,  0.004227f, -0.002438f,
    -0.004200f, -0.001576f,  0.001580f,  0.002198f,
     0.000337f, -0.001695f, -0.001919f, -0.000392f,
     0.001238f,  0.001516f,  0.000454f, -0.000741f,
    -0.000967f
};

/* ── RRC polyphase matched filter (decimation by SPS=4) ─────────────
 * Processes one sample at a time.
 * Returns true and writes to *out every SPS input samples.
 *
 * Uses a circular shift register in BRAM (HLS maps this automatically).
 */
static bool rrc_filter_decim(fixp_t i_in, fixp_t q_in,
                              fixp_t& i_out, fixp_t& q_out, bool rst)
{
#pragma HLS INLINE
    static fixp_t delay_i[NTAPS];
    static fixp_t delay_q[NTAPS];
#pragma HLS ARRAY_PARTITION variable=delay_i complete
#pragma HLS ARRAY_PARTITION variable=delay_q complete

    /* Reset clears the pulse history to the power-on state (all zero). `rst`
     * is a parameter rather than a global so each stage owns and clears its
     * own state -- the failure mode of a reset path is forgetting one field,
     * and that is much easier to spot when the clear sits next to the
     * declaration. There is no default argument on purpose: a new call site
     * has to say what it means. */
    if (rst) {
        for (int k = 0; k < NTAPS; k++) {
#pragma HLS UNROLL
            delay_i[k] = 0;
            delay_q[k] = 0;
        }
        i_out = 0;
        q_out = 0;
        return false;
    }

    /* Shift register */
    for (int k = NTAPS-1; k > 0; k--) {
#pragma HLS UNROLL
        delay_i[k] = delay_i[k-1];
        delay_q[k] = delay_q[k-1];
    }
    delay_i[0] = i_in;
    delay_q[0] = q_in;

    /* No decimation here.
     *
     * This used to drop 3 of every 4 samples on a fixed phase, and
     * timing_recovery below then decimated by 4 again -- 16x total against a
     * symbol rate that is only 4x the sample rate. Measured in C simulation:
     * 6016 input samples produced 94 output bytes where 376 were expected,
     * exactly the factor of 4 too few.
     *
     * A matched filter belongs at the full sample rate; choosing WHICH sample
     * represents each symbol is timing recovery's job, and it needs all four
     * phases to make that choice. Picking a fixed phase here both broke the
     * rate and denied the timing loop the samples it exists to compare.
     *
     * FIR: fully unrolled → single-cycle multiply-accumulate */
    acc_t acc_i = 0, acc_q = 0;
    for (int k = 0; k < NTAPS; k++) {
#pragma HLS UNROLL
        acc_i += (acc_t)(delay_i[k] * RRC_H[k]);
        acc_q += (acc_t)(delay_q[k] * RRC_H[k]);
    }

    i_out = (fixp_t)acc_i;
    q_out = (fixp_t)acc_q;
    return true;
}

/* ── AGC (digital automatic gain control) ───────────────────────────
 * Simple first-order feedback: scale → measure envelope → adjust gain.
 * Bandwidth 2^-10 ≈ 0.001 (slow enough to track fading, fast enough
 * to acquire on preamble).
 */
