CONFIG_VERSION=2
MODE=raw-eth
IFACE=eth0
SAMPLE_RATE=15360000
FREQUENCY=444000000
RX_FREQUENCY=434000000
DIFF_MODE=1
STATS_S=15
NODE_ID=465429558
TX_RF_BANDWIDTH=4000000
RX_RF_BANDWIDTH=4000000
TX_ATTENUATION_DB=0
RX_GAIN_MODE=slow_attack
PROBE_INTERVAL_S=5
