#!/usr/bin/env python3
"""16-QAM symbol-domain BER-vs-SNR characterization for the REAL FPGA
demapper (fpga/rtl/qam16_demapper.v), via the qam16_harness test bitstream
built this project (adi-hdl/projects/qam16_harness/). Produces the first
real hardware data point for docs/mission-network.md's F07 row, which
explicitly lists "hardware EVM/BER/PER sweeps" as still missing.

NOT an RF qualification: this injects synthetic AWGN directly into the
demapper's digital I/Q input over AXI-Lite, the same way
src/tools/modem_characterize.cpp characterizes the host liquid-dsp path
(whose own header carries the identical disclaimer) -- there is no real
over-the-air channel, antenna, or RF front end involved. What it DOES prove:
the demapper's decision logic (not just its exact-zero-noise lattice points,
already proven in tests/tb_axi_qam16_test_harness_hw.v and on real hardware)
behaves correctly across a realistic noise waterfall, using the EXACT same
AWGN model already used for this project's AMC threshold calibration
(docs/reports/mission-awgn.csv, generated by modem_characterize.cpp).

Usage:
    1. Build and flash adi-hdl/projects/qam16_harness/ to a unit (see
       [[rs-harness-on-device-test]] / the qam16-rtl-precedes-qam64-fpga
       memory for the exact safe flash/revert procedure -- stop
       sdr_bridge/appliance_supervise first, load via fpga_manager under a
       distinct filename, never touch QSPI flash, revert via `reboot -f`).
    2. Run this script locally: it generates the noisy vectors, uploads a
       small busybox-shell driver + vectors file over scp, runs the sweep
       over ssh, and reports hardware BER vs the host reference's BER for
       the IDENTICAL noise realizations (not just a separately-computed
       curve -- so any mismatch is a real discrepancy, not sampling noise).

python3 fpga/probe/qam16_ber_sweep.py --host root@192.168.2.1 --password analog
"""
import argparse
import math
import random
import subprocess
import sys
import tempfile
import os

LEVELS = [-7773, -2591, 2591, 7773]  # index 0..3, matches qam16_demapper.v
DEFAULT_SNR_POINTS = [6, 12, 18, 24, 30, 36]  # matches modem_characterize.cpp's sweep


def gray(b):
    return b ^ (b >> 1)


def gray_to_binary(g):
    # matches qam16_mapper.v's amplitude() function
    b1 = (g >> 1) & 1
    b0 = ((g >> 1) ^ g) & 1
    return (b1 << 1) | b0


def index(x):
    # matches qam16_demapper.v's index() function exactly
    if x < -5182:
        return 0
    elif x < 0:
        return 1
    elif x < 5182:
        return 2
    else:
        return 3


def ideal_iq(label):
    gi = (label >> 2) & 3
    gq = label & 3
    return LEVELS[gray_to_binary(gi)], LEVELS[gray_to_binary(gq)]


def decode(i, q):
    return (gray(index(i)) << 2) | gray(index(q))


def snr_sigma(snr_db):
    # IDENTICAL formula to modem_characterize.cpp's AWGN model (normalized
    # float domain, unit constellation energy), scaled to this project's
    # Q2.13 fixed-point convention (*8192).
    return math.sqrt(10 ** (-snr_db / 10) / 2) * 8192


def generate_vectors(snr_points, n_per_point, seed):
    rng = random.Random(seed)
    blocks = []
    for snr in snr_points:
        sigma = snr_sigma(snr)
        rows = []
        for _ in range(n_per_point):
            label = rng.randrange(16)
            ii, qq = ideal_iq(label)
            ni = max(-32768, min(32767, round(ii + rng.gauss(0, sigma))))
            nq = max(-32768, min(32767, round(qq + rng.gauss(0, sigma))))
            rows.append((label, ni & 0xFFFF, nq & 0xFFFF, decode(ni, nq)))
        blocks.append((snr, rows))
    return blocks


DRIVER_SH = r"""#!/bin/sh
BASE=0x43C60000
PUSH_I=$((BASE+0x14))
PUSH_Q=$((BASE+0x18))
DEMAP_STATUS=$((BASE+0x1C))
POP_SYM=$((BASE+0x20))
POP_ERROR=$((BASE+0x24))
VECTORS=/tmp/qam16_ber_vectors.txt
OUT=/tmp/qam16_ber_results.txt
> "$OUT"
while read -r label ni nq hostdec; do
  case "$label" in
    \#*) echo "#" >> "$OUT"; continue ;;
  esac
  while true; do
    st=$(devmem $DEMAP_STATUS); r=$(( st & 1 )); [ $r -ne 0 ] && break
  done
  devmem $PUSH_I w 0x$ni
  devmem $PUSH_Q w 0x$nq
  while true; do
    st=$(devmem $DEMAP_STATUS); mv=$(( (st>>1)&1 )); [ $mv -ne 0 ] && break
  done
  hw=$(devmem $POP_SYM)
  devmem $POP_ERROR > /dev/null
  echo "$label $ni $nq $hostdec $hw" >> "$OUT"
done < "$VECTORS"
echo "DONE"
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", default="root@192.168.2.1")
    ap.add_argument("--password", default="analog")
    ap.add_argument("--snr", type=int, nargs="+", default=DEFAULT_SNR_POINTS)
    ap.add_argument("--symbols-per-point", type=int, default=1000)
    ap.add_argument("--seed", type=int, default=640016)
    args = ap.parse_args()

    blocks = generate_vectors(args.snr, args.symbols_per_point, args.seed)

    with tempfile.TemporaryDirectory() as work:
        vectors_path = os.path.join(work, "vectors.txt")
        driver_path = os.path.join(work, "driver.sh")
        with open(vectors_path, "w") as f:
            for snr, rows in blocks:
                f.write(f"# SNR={snr}\n")
                for label, ni, nq, hostdec in rows:
                    f.write(f"{label:x} {ni:04x} {nq:04x} {hostdec:x}\n")
        with open(driver_path, "w") as f:
            f.write(DRIVER_SH)

        def scp(src, dst):
            subprocess.run(["sshpass", "-p", args.password, "scp", "-O",
                             "-o", "PubkeyAuthentication=no", "-o", "PreferredAuthentications=password",
                             src, f"{args.host}:{dst}"], check=True)

        def ssh(cmd):
            return subprocess.run(["sshpass", "-p", args.password, "ssh",
                                    "-o", "PubkeyAuthentication=no", "-o", "PreferredAuthentications=password",
                                    "-o", "ConnectTimeout=8", args.host, cmd],
                                   check=True, capture_output=True, text=True)

        print("Uploading vectors + driver...", file=sys.stderr)
        scp(vectors_path, "/tmp/qam16_ber_vectors.txt")
        scp(driver_path, "/tmp/qam16_ber_hw_test.sh")
        print(f"Running sweep ({sum(len(r) for _, r in blocks)} symbols)...", file=sys.stderr)
        ssh("sh /tmp/qam16_ber_hw_test.sh")
        results_path = os.path.join(work, "results.txt")
        subprocess.run(["sshpass", "-p", args.password, "scp", "-O",
                         "-o", "PubkeyAuthentication=no", "-o", "PreferredAuthentications=password",
                         f"{args.host}:/tmp/qam16_ber_results.txt", results_path], check=True)
        ssh("rm -f /tmp/qam16_ber_vectors.txt /tmp/qam16_ber_results.txt /tmp/qam16_ber_hw_test.sh")

        snr_idx = -1
        current_snr = None
        data = {snr: [] for snr, _ in blocks}
        with open(results_path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                if line.startswith("#"):
                    snr_idx += 1
                    current_snr = args.snr[snr_idx]
                    continue
                label, ni, nq, hostdec, hwdec = line.split()
                data[current_snr].append((int(label, 16), int(hostdec, 16), int(hwdec, 16)))

    print(f"{'SNR(dB)':>8} {'HW_BER':>10} {'HOST_BER':>10} {'mismatches':>11} {'symbols':>8}")
    total_mismatches = 0
    for snr, rows in data.items():
        hw_errs = sum(bin(label ^ hw).count("1") for label, host, hw in rows)
        host_errs = sum(bin(label ^ host).count("1") for label, host, hw in rows)
        mism = sum(1 for _, host, hw in rows if host != hw)
        total_mismatches += mism
        total_bits = len(rows) * 4
        print(f"{snr:>8} {hw_errs/total_bits:>10.5f} {host_errs/total_bits:>10.5f} {mism:>11} {len(rows):>8}")
    print(f"\ntotal host/hardware decode mismatches: {total_mismatches}")
    return 0 if total_mismatches == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
